### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by PolishedStaple** [hippich/PHPMailer-BMH#18]
I've been using PHPMailer for about 6 months now to send out around 100,000 emails per month.  I just discovered the BMH code on GitHub today.  Are they two separate products?  Should I install BHM inside my existing PHPMailer folder on the server?

Thanks!

**Comment by PolishedStaple** [comment]
I got sidetracked after submitting this post in 2014, but now I'm back.  Is this project still being worked on?  Is it still a viable option all these years later?

**Comment by hippich** [comment]
I haven't worked on anything related for quite a while. I would recommend researching forks of this and similar repos to find something up to date.
